repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: ["-l", "80", "-t", "py34"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        exclude: "conftest.py|^doc"
-   repo: https://github.com/codespell-project/codespell
    rev: 'v2.2.4'
    hooks:
    -   id: codespell
        args: ["-I", "codespell.txt"]

ci:
    autoupdate_schedule: monthly
